### ISSUE TITLE
why not 1.0.0?

### ISSUE THREAD

**Issue by Kikobeats** [juliangruber/is-type#2]
simple question :)

**Comment by juliangruber** [comment]
curious, why would you want a 1.0.0?

**Comment by Kikobeats** [comment]
I feel that the major portion of library node authors feel unsafe when establishing a version for libraries. Node 0.10 is stable such as node 5.0.0. 

Why since two years from the last code commit do you consider the library unstable?

**Comment by juliangruber** [comment]
a package's version per se has nothing to do with its stability. `1.0.0` according to semver simply means "the first breaking change happened".

With newer packages I usually just publish a `1.0.0` first, to get this problem out of the way, but for older ones I don't think the cost of a major version bump is worth it.

**Comment by Kikobeats** [comment]
👍
